//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursach
{
    using System;
    using System.Collections.Generic;
    
    public partial class Load
    {
        public int Load_ID { get; set; }
        public int Teacher_ID { get; set; }
        public int Subject_ID { get; set; }
        public int Academic_Year { get; set; }
        public int Semestr { get; set; }
        public string Grupa { get; set; }
        public int Kol_students { get; set; }
        public string Final_control { get; set; }
    
        public virtual Subject Subject { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
